# TODO: Remove this temporary workspace once the crate functionality has been
# migrated to a more general-use tooling set. These tools have been added as a
# stop-gap to ease the development of apps within this repo.
[workspace]
members = [
  "crates/*"
]
resolver = "2"

[workspace.dependencies]
clap = { versio = "4", features = ["derive"] }
essential-hash = { git = "ssh://git@github.com/essential-contributions/essential-base.git" }
essential-sign = { git = "ssh://git@github.com/essential-contributions/essential-base.git" }
essential-types = { git = "ssh://git@github.com/essential-contributions/essential-base.git" }
secp256k1 = { version = "0.29", features = ["rand-std", "recovery"] }
serde_json = "1"

